data:
  raw_path: "data/raw/housing.csv"
  # Nouveaux chemins
  train_path: "data/processed/train.csv"
  test_path: "data/processed/test.csv"
  preprocessor_path: "data/processed/preprocessor.pkl" # L'objet de transformation
  test_size: 0.2
  random_state: 42

validation:
  max_house_age: 100
  min_income: 0

mlflow:
  experiment_name: "house-pricing-prod"
